<?php

/**
 * @file
 * IXI: XML Importer file
 *
 * This modules allows for the upload of XML exported to create new content
 * nodes.
 */

/**
 * Implements hook_help().
 */
function ixi_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ixi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import XML as new content nodes.') . '</p>';
      $output .= '<h3>' . t('Configuration') . '</h3>';
      $output .= '<p>' . t('You select a group content type and fields and these fields are added into the upload form when uploading a new archive.') . '</p>';
      $output .= '<p>' . t('Note that the fields that you select are generated as if they were in the add new content form.') . '</p>';
      $output .= '<h3>' . t('General Information') . '</h3>';
      $output .= '<p>' . t('The module saves uploaded archives in the private files folder under &quot;ixi_archives&quot; so that they aren\'t exposed to the public prior to processing.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function ixi_permission() {
  return array(
    'administer xml import' => array(
      'title' => t('Administer XML Import'),
      'description' => t('Configure the XML importer settings.'),
    ),
    'perform xml import' => array(
      'title' => t('Perform XML Import'),
      'description' => t('Upload and process an archive of XML files.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ixi_menu() {
  $items['admin/config/ixi'] = array(
    'title' => 'XML Import',
    'description' => 'Configure the XML Importer.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ixi_config_form'),
    'access arguments' => array('administer xml import'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ixi.admin.inc',
  );
  $items['admin/reports/status/ixi/archive_directory'] = array(
    'title' => 'Recreate archive directory',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ixi_recreate_archive_directory_form'),
    'access arguments' => array('administer xml import'),
    'type' => MENU_CALLBACK,
    'file' => 'ixi.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_cron().
 */
function ixi_cron() {
  if (variable_get('ixi_garbage_collect') == 1) {
    $sql = "SELECT iau.xid, iau.fid FROM {ixi_archive_uploads} iau WHERE iau.processed = '1'";
    $result = db_query($sql);
    if ($result) {
      while ($row = $result->fetchAssoc()) {
        $o_sql = "SELECT ixq.id FROM {ixi_xml_queue} ixq WHERE ixq.xid = :xid";
        $o_result = db_query($o_sql, array(':xid' => $row['xid']));
        foreach ($o_result as $o_row) {
          db_delete('ixi_overrides')
            ->condition('id', $o_row->id)
            ->execute();
        }
        $file = file_load($row['fid']);
        file_delete($file);
        db_delete('ixi_archive_uploads')
          ->condition('xid', $row['xid'])
          ->execute();
        db_delete('ixi_xml_queue')
          ->condition('xid', $row['xid'])
          ->execute();
        watchdog('ixi', 'Deleted file with fid: %fid and associated records: %xid.', array('%fid' => $row['fid'], '%xid' => $row['xid']), WATCHDOG_DEBUG);
      }
    }
  }
}
